{
 "title": "GIn vs Echo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gin response time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"gin\"}[2s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"gin\"}[2s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"gin\"}[2s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"gin\"}[2s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"gin\"}[2s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Echo response time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"echo\"}[2s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"echo\"}[2s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"echo\"}[2s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"echo\"}[2s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"echo\"}[2s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gin RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"gin\"}[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Echo RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"echo\"}[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alloc bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[2s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}