version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: eschool
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis
    command: redis-server
    volumes:
      - ./.data/redis:/var/lib/redis
      - ./.data/redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
