// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/paw1a/eschool/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// CertificateRepository is an autogenerated mock type for the ICertificateRepository type
type CertificateRepository struct {
	mock.Mock
}

// CreateCourseCertificate provides a mock function with given fields: ctx, userID, courseID
func (_m *CertificateRepository) CreateCourseCertificate(ctx context.Context, userID int64, courseID int64) (domain.Certificate, error) {
	ret := _m.Called(ctx, userID, courseID)

	var r0 domain.Certificate
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) domain.Certificate); ok {
		r0 = rf(ctx, userID, courseID)
	} else {
		r0 = ret.Get(0).(domain.Certificate)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *CertificateRepository) FindAll(ctx context.Context) ([]domain.Certificate, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Certificate
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Certificate); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Certificate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, certificateID
func (_m *CertificateRepository) FindByID(ctx context.Context, certificateID int64) (domain.Certificate, error) {
	ret := _m.Called(ctx, certificateID)

	var r0 domain.Certificate
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Certificate); ok {
		r0 = rf(ctx, certificateID)
	} else {
		r0 = ret.Get(0).(domain.Certificate)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, certificateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserCertificates provides a mock function with given fields: ctx, userID
func (_m *CertificateRepository) FindUserCertificates(ctx context.Context, userID int64) ([]domain.Certificate, error) {
	ret := _m.Called(ctx, userID)

	var r0 []domain.Certificate
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Certificate); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Certificate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCertificateRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCertificateRepository creates a new instance of CertificateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCertificateRepository(t mockConstructorTestingTNewCertificateRepository) *CertificateRepository {
	mock := &CertificateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
