// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/paw1a/eschool/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// CourseRepository is an autogenerated mock type for the ICourseRepository type
type CourseRepository struct {
	mock.Mock
}

// AddCourseStudent provides a mock function with given fields: ctx, studentID, courseID
func (_m *CourseRepository) AddCourseStudent(ctx context.Context, studentID domain.ID, courseID domain.ID) error {
	ret := _m.Called(ctx, studentID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for AddCourseStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID, domain.ID) error); ok {
		r0 = rf(ctx, studentID, courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddCourseTeacher provides a mock function with given fields: ctx, teacherID, courseID
func (_m *CourseRepository) AddCourseTeacher(ctx context.Context, teacherID domain.ID, courseID domain.ID) error {
	ret := _m.Called(ctx, teacherID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for AddCourseTeacher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID, domain.ID) error); ok {
		r0 = rf(ctx, teacherID, courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, course
func (_m *CourseRepository) Create(ctx context.Context, course domain.Course) (domain.Course, error) {
	ret := _m.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Course) (domain.Course, error)); ok {
		return rf(ctx, course)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Course) domain.Course); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Get(0).(domain.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Course) error); ok {
		r1 = rf(ctx, course)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, courseID
func (_m *CourseRepository) Delete(ctx context.Context, courseID domain.ID) error {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = rf(ctx, courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *CourseRepository) FindAll(ctx context.Context) ([]domain.Course, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Course, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Course); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, courseID
func (_m *CourseRepository) FindByID(ctx context.Context, courseID domain.ID) (domain.Course, error) {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) (domain.Course, error)); ok {
		return rf(ctx, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) domain.Course); ok {
		r0 = rf(ctx, courseID)
	} else {
		r0 = ret.Get(0).(domain.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindStudentCourses provides a mock function with given fields: ctx, studentID
func (_m *CourseRepository) FindStudentCourses(ctx context.Context, studentID domain.ID) ([]domain.Course, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for FindStudentCourses")
	}

	var r0 []domain.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) ([]domain.Course, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) []domain.Course); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTeacherCourses provides a mock function with given fields: ctx, teacherID
func (_m *CourseRepository) FindTeacherCourses(ctx context.Context, teacherID domain.ID) ([]domain.Course, error) {
	ret := _m.Called(ctx, teacherID)

	if len(ret) == 0 {
		panic("no return value specified for FindTeacherCourses")
	}

	var r0 []domain.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) ([]domain.Course, error)); ok {
		return rf(ctx, teacherID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) []domain.Course); ok {
		r0 = rf(ctx, teacherID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = rf(ctx, teacherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, course
func (_m *CourseRepository) Update(ctx context.Context, course domain.Course) (domain.Course, error) {
	ret := _m.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Course) (domain.Course, error)); ok {
		return rf(ctx, course)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Course) domain.Course); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Get(0).(domain.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Course) error); ok {
		r1 = rf(ctx, course)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, courseID, status
func (_m *CourseRepository) UpdateStatus(ctx context.Context, courseID domain.ID, status domain.CourseStatus) error {
	ret := _m.Called(ctx, courseID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID, domain.CourseStatus) error); ok {
		r0 = rf(ctx, courseID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseRepository creates a new instance of CourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepository {
	mock := &CourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
