// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/paw1a/eschool/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	port "github.com/paw1a/eschool/internal/core/port"
)

// LessonRepository is an autogenerated mock type for the ILessonRepository type
type LessonRepository struct {
	mock.Mock
}

// AddLessonTests provides a mock function with given fields: ctx, tests
func (_m *LessonRepository) AddLessonTests(ctx context.Context, tests []domain.Test) error {
	ret := _m.Called(ctx, tests)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Test) error); ok {
		r0 = rf(ctx, tests)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, lesson
func (_m *LessonRepository) Create(ctx context.Context, lesson domain.Lesson) (domain.Lesson, error) {
	ret := _m.Called(ctx, lesson)

	var r0 domain.Lesson
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lesson) domain.Lesson); ok {
		r0 = rf(ctx, lesson)
	} else {
		r0 = ret.Get(0).(domain.Lesson)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lesson) error); ok {
		r1 = rf(ctx, lesson)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, lessonID
func (_m *LessonRepository) Delete(ctx context.Context, lessonID domain.ID) error {
	ret := _m.Called(ctx, lessonID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = rf(ctx, lessonID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLessonTest provides a mock function with given fields: ctx, testID
func (_m *LessonRepository) DeleteLessonTest(ctx context.Context, testID domain.ID) error {
	ret := _m.Called(ctx, testID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = rf(ctx, testID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *LessonRepository) FindAll(ctx context.Context) ([]domain.Lesson, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Lesson
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Lesson); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Lesson)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, lessonID
func (_m *LessonRepository) FindByID(ctx context.Context, lessonID domain.ID) (domain.Lesson, error) {
	ret := _m.Called(ctx, lessonID)

	var r0 domain.Lesson
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) domain.Lesson); ok {
		r0 = rf(ctx, lessonID)
	} else {
		r0 = ret.Get(0).(domain.Lesson)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = rf(ctx, lessonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindCourseLessons provides a mock function with given fields: ctx, courseID
func (_m *LessonRepository) FindCourseLessons(ctx context.Context, courseID domain.ID) ([]domain.Lesson, error) {
	ret := _m.Called(ctx, courseID)

	var r0 []domain.Lesson
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) []domain.Lesson); ok {
		r0 = rf(ctx, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Lesson)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLessonTests provides a mock function with given fields: ctx, lessonID
func (_m *LessonRepository) FindLessonTests(ctx context.Context, lessonID domain.ID) ([]domain.Test, error) {
	ret := _m.Called(ctx, lessonID)

	var r0 []domain.Test
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID) []domain.Test); ok {
		r0 = rf(ctx, lessonID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Test)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = rf(ctx, lessonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLessonTest provides a mock function with given fields: ctx, testID, param
func (_m *LessonRepository) UpdateLessonTest(ctx context.Context, testID domain.ID, param port.UpdateTestParam) (domain.Test, error) {
	ret := _m.Called(ctx, testID, param)

	var r0 domain.Test
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID, port.UpdateTestParam) domain.Test); ok {
		r0 = rf(ctx, testID, param)
	} else {
		r0 = ret.Get(0).(domain.Test)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.ID, port.UpdateTestParam) error); ok {
		r1 = rf(ctx, testID, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLessonTheory provides a mock function with given fields: ctx, lessonID, param
func (_m *LessonRepository) UpdateLessonTheory(ctx context.Context, lessonID domain.ID, param port.UpdateTheoryParam) error {
	ret := _m.Called(ctx, lessonID, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID, port.UpdateTheoryParam) error); ok {
		r0 = rf(ctx, lessonID, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLessonVideo provides a mock function with given fields: ctx, lessonID, param
func (_m *LessonRepository) UpdateLessonVideo(ctx context.Context, lessonID domain.ID, param port.UpdateVideoParam) error {
	ret := _m.Called(ctx, lessonID, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ID, port.UpdateVideoParam) error); ok {
		r0 = rf(ctx, lessonID, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewLessonRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewLessonRepository creates a new instance of LessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLessonRepository(t mockConstructorTestingTNewLessonRepository) *LessonRepository {
	mock := &LessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
