// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/paw1a/eschool/internal/core/domain"
	dto "github.com/paw1a/eschool/internal/core/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// SchoolRepository is an autogenerated mock type for the ISchoolRepository type
type SchoolRepository struct {
	mock.Mock
}

// AddSchoolTeacher provides a mock function with given fields: ctx, schoolID, teacherID
func (_m *SchoolRepository) AddSchoolTeacher(ctx context.Context, schoolID int64, teacherID int64) error {
	ret := _m.Called(ctx, schoolID, teacherID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, schoolID, teacherID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUserSchool provides a mock function with given fields: ctx, schoolDTO, userID
func (_m *SchoolRepository) CreateUserSchool(ctx context.Context, schoolDTO dto.CreateSchoolDTO, userID int64) (domain.School, error) {
	ret := _m.Called(ctx, schoolDTO, userID)

	var r0 domain.School
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateSchoolDTO, int64) domain.School); ok {
		r0 = rf(ctx, schoolDTO, userID)
	} else {
		r0 = ret.Get(0).(domain.School)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateSchoolDTO, int64) error); ok {
		r1 = rf(ctx, schoolDTO, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, schoolID
func (_m *SchoolRepository) Delete(ctx context.Context, schoolID int64) error {
	ret := _m.Called(ctx, schoolID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, schoolID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *SchoolRepository) FindAll(ctx context.Context) ([]domain.School, error) {
	ret := _m.Called(ctx)

	var r0 []domain.School
	if rf, ok := ret.Get(0).(func(context.Context) []domain.School); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.School)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, schoolID
func (_m *SchoolRepository) FindByID(ctx context.Context, schoolID int64) (domain.School, error) {
	ret := _m.Called(ctx, schoolID)

	var r0 domain.School
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.School); ok {
		r0 = rf(ctx, schoolID)
	} else {
		r0 = ret.Get(0).(domain.School)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, schoolID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserSchool provides a mock function with given fields: ctx, schoolID, schoolDTO, userID
func (_m *SchoolRepository) UpdateUserSchool(ctx context.Context, schoolID int64, schoolDTO dto.UpdateSchoolDTO, userID int64) (domain.School, error) {
	ret := _m.Called(ctx, schoolID, schoolDTO, userID)

	var r0 domain.School
	if rf, ok := ret.Get(0).(func(context.Context, int64, dto.UpdateSchoolDTO, int64) domain.School); ok {
		r0 = rf(ctx, schoolID, schoolDTO, userID)
	} else {
		r0 = ret.Get(0).(domain.School)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, dto.UpdateSchoolDTO, int64) error); ok {
		r1 = rf(ctx, schoolID, schoolDTO, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSchoolRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewSchoolRepository creates a new instance of SchoolRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSchoolRepository(t mockConstructorTestingTNewSchoolRepository) *SchoolRepository {
	mock := &SchoolRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
