// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/paw1a/eschool/internal/core/domain"
	dto "github.com/paw1a/eschool/internal/core/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the IUserRepository type
type UserRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userDTO
func (_m *UserRepository) Create(ctx context.Context, userDTO dto.CreateUserDTO) (domain.User, error) {
	ret := _m.Called(ctx, userDTO)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserDTO) domain.User); ok {
		r0 = rf(ctx, userDTO)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateUserDTO) error); ok {
		r1 = rf(ctx, userDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, userID
func (_m *UserRepository) Delete(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *UserRepository) FindAll(ctx context.Context) ([]domain.User, error) {
	ret := _m.Called(ctx)

	var r0 []domain.User
	if rf, ok := ret.Get(0).(func(context.Context) []domain.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCredentials provides a mock function with given fields: ctx, email, password
func (_m *UserRepository) FindByCredentials(ctx context.Context, email string, password string) (domain.User, error) {
	ret := _m.Called(ctx, email, password)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, userID
func (_m *UserRepository) FindByID(ctx context.Context, userID int64) (domain.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserInfo provides a mock function with given fields: ctx, userID
func (_m *UserRepository) FindUserInfo(ctx context.Context, userID int64) (dto.UserInfo, error) {
	ret := _m.Called(ctx, userID)

	var r0 dto.UserInfo
	if rf, ok := ret.Get(0).(func(context.Context, int64) dto.UserInfo); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(dto.UserInfo)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, userID, userDTO
func (_m *UserRepository) Update(ctx context.Context, userID int64, userDTO dto.UpdateUserDTO) (domain.User, error) {
	ret := _m.Called(ctx, userID, userDTO)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, int64, dto.UpdateUserDTO) domain.User); ok {
		r0 = rf(ctx, userID, userDTO)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, dto.UpdateUserDTO) error); ok {
		r1 = rf(ctx, userID, userDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
