jwt:
  accessTokenTime: 60 # minutes
  refreshTokenTime: 86400 # minutes, (86400 == 60 days)
server:
  host: localhost
  port: 8080
yoomoney:
  scheme: https
  host: yoomoney.ru
  path: /quickpay/confirm
